test
js-tasks-ru/htmlcss-20230714_evgeniav pull request #10
Opened 2023-08-09 06:29 UTC by jennievv

2023-08-09 06:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-09 06:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-09 10:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-09 10:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-09 10:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-09 10:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-09 11:00 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-18 10:52 UTC, GSemikozov requested changes

2023-08-18 10:52 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    margin: 100px 0 0 100px;
Ни в коем случае марджины на уровне блока не задаем)

2023-08-18 10:52 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    top: -55px;
Bottom: calc(100% + 8px)

2023-08-21 18:51 UTC, GSemikozov approved these changes

2023-08-21 18:51 UTC, merged