modal
js-tasks-ru/htmlcss-20230714_evgeniav pull request #11
Opened 2023-08-17 15:04 UTC by jennievv

2023-08-17 15:05 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-17 16:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-17 16:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-17 19:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-17 20:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-18 13:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-18 14:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-21 18:53 UTC, GSemikozov requested changes

2023-08-21 18:53 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.button_modal{
модификатор блока Кнопка в блока Модал? ошибка, так делать не надо, удалим

2023-08-21 18:53 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    background: rgba(196, 196, 196, 0.5);
position: fixed

2023-08-22 06:17 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-22 06:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-22 06:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-22 06:29 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-22 06:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-22 06:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-22 07:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-22 09:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-22 19:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-30 22:35 UTC, GSemikozov requested changes

2023-08-30 22:35 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.button_modal{
удалим

2023-08-30 22:35 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    background: rgba(196, 196, 196, 0.5);
все еще актуально

2023-09-12 17:40 UTC, GSemikozov approved these changes

2023-09-12 17:40 UTC, merged