background-image
js-tasks-ru/htmlcss-20230714_evgeniav pull request #13
Opened 2023-08-23 11:57 UTC by jennievv

2023-08-23 11:58 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-24 21:46 UTC, GSemikozov requested changes

2023-08-24 21:46 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media (max-width: 2560px) {
лишний медиа=запрос, ставим forest_2560.jpg картинкой по умолчанию

2023-08-26 20:29 UTC, GSemikozov approved these changes

2023-08-26 20:30 UTC, merged