burger-menu
js-tasks-ru/htmlcss-20230714_evgeniav pull request #21
Opened 2023-09-21 08:59 UTC by jennievv

2023-09-21 09:06 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-21 09:08 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-09-21 20:55 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +        top: 64px;
0

2023-09-21 20:55 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +    .container {
что-то лишнее

2023-09-21 20:55 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +    .burger-menu__mode {
лишний элемент, тут его не делаем

2023-09-21 20:55 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +    .burger-menu__li_last-li {
.burger-menu__li:last-child

2023-09-21 20:55 UTC, GSemikozov commented on 09-lection7/01-burger-menu/index.html
> +        <button class="burger-menu__icon burger-menu__icon_open" id="burger-menu-open">
это не элемент блока burger-menu, так что все классы применимые к этой кнопке надо выпилить и не использовать)

2023-09-25 07:40 UTC, GSemikozov requested changes

2023-09-25 07:40 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +    .header__toggle-burger-menu{
если речь об элементе хедера - то в хедере его и надо описывать)

2023-09-25 07:40 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +    .burger-menu__close .burger-menu__svg{
просто .burger-menu__svg

2023-09-25 08:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-25 21:21 UTC, GSemikozov approved these changes

2023-09-25 21:21 UTC, merged