Main page (desk + mobile)
js-tasks-ru/htmlcss-20230714_evgeniav pull request #27
Opened 2023-09-30 11:38 UTC by jennievv

2023-09-30 11:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-01 19:55 UTC, GSemikozov requested changes

2023-10-01 19:55 UTC, GSemikozov commented on components/burger-menu/burger-menu.css
> +    .burger-menu__close .burger-menu__svg{
просто .burger-menu__svg

2023-10-01 19:55 UTC, GSemikozov commented on components/tabs/tabs.css
> +.tabs__scroller_margin-left{
это надо только на мобилке?
скроллер можно завернуть в обычный container

2023-10-01 19:55 UTC, GSemikozov commented on components/tabs/tabs.css
> +    position: absolute;
по умолчанию ведь `transform: translateX(-100vw);`, не совсем понятно зачем `position: absolute;`

2023-10-02 18:53 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-02 19:12 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-10-02 19:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-10-15 17:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-10-15 17:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-10-22 19:13 UTC, GSemikozov approved these changes

2023-10-22 19:13 UTC, merged