main-page
js-tasks-ru/htmlcss-20230714_evgeniav pull request #3
Opened 2023-07-22 21:12 UTC by jennievv

Не понимаю почему не работают файлы стилей, которые я подключила в main.css через import, пути вроде верные

2023-07-22 21:12 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-07-23 04:56 UTC, GSemikozov requested changes

2023-07-23 04:56 UTC, GSemikozov commented on components/footer/footer.css
> +.page__footer {
просто footer

2023-07-23 04:56 UTC, GSemikozov commented on components/footer/footer.css
> +.page__subtitle {
.footer__subtitle

2023-07-23 04:56 UTC, GSemikozov commented on components/footer/footer.css
> +.page__text {
.footer__text

2023-07-23 04:56 UTC, GSemikozov commented on components/footer/footer.css
> +.page__footer {
мы ведь описываем блок Футер, а не элемент блока Страница

2023-07-23 04:56 UTC, GSemikozov commented on components/footer/footer.css
> +    max-width: 640px;
это ограничение ширины актуально только для текста внутри)

2023-07-23 04:56 UTC, GSemikozov commented on components/footer/footer.css
> +    height: 384px;
высоту не стоит ограничивать

2023-07-23 04:56 UTC, GSemikozov commented on components/header/header.css
> +.page__header {
просто header

2023-07-23 04:56 UTC, GSemikozov commented on components/header/header.css
> +    height: 237px;
высоту не ограничиваем

2023-07-23 04:56 UTC, GSemikozov commented on components/main/main.css
> +.page__main {
просто .main

2023-07-23 04:56 UTC, GSemikozov commented on components/page/page.css
> +.wrapper {
.page

2023-07-23 04:56 UTC, GSemikozov commented on components/page/page.css
> +.container{
унесем как отдельный блок

2023-07-23 04:56 UTC, GSemikozov commented on components/page/page.css
> +.page__row{
пока - лишнее, удалим

2023-07-23 04:56 UTC, GSemikozov commented on index.html
> +        <div class="wrapper">
лишний враппер, можно сразу page

2023-07-23 04:56 UTC, GSemikozov commented on index.html
> +                <div class="container">
контейнер будет использовать для выравнивания контента уже внутри самих макро блоков

2023-07-23 04:56 UTC, GSemikozov commented on index.html
> +                        <div class="page__header">
`<header class="header">`

2023-07-23 04:56 UTC, GSemikozov commented on index.html
> +                        <div class="page__main">
`<main`

2023-07-23 04:56 UTC, GSemikozov commented on index.html
> +                        <div class="page__footer">
`<footer`

2023-07-24 07:21 UTC, jennievv commented on index.html
> +                <div class="container">
то есть мне сделать вот так? как пример взяла header

`<header class="header">
     <div class="container">
         <h1 class="header__title">Reusable component library</h1>
      <div>
</header>`

2023-07-24 07:26 UTC, jennievv commented on index.html
> +                <div class="container">
то есть мне сделать вот так? как пример взяла header

```html
<header class="header">
     <div class="container">
         <h1 class="header__title">Reusable component library</h1>
      <div>
</header>
```

2023-07-28 15:05 UTC, GSemikozov commented on index.html
> +                <div class="container">
ага

2023-08-01 15:30 UTC, GSemikozov requested changes

2023-08-01 15:30 UTC, GSemikozov commented on components/container/container.css
> +    margin: 0 160px;
`0 auto`

2023-08-01 15:30 UTC, GSemikozov commented on components/header/header.css
> +    min-height: 237px;
лишнее

2023-08-01 15:30 UTC, GSemikozov commented on components/page/page.css
> +.container{
а отсюда тогда удалим)

2023-08-18 10:48 UTC, GSemikozov requested changes

2023-08-18 10:48 UTC, GSemikozov commented on pages/component-page/container/container.css
> +.container{
Для другой страницы не нужно создавать такие же компоненты - все компоненты лежат в корне в папке components, так что надо исправить

2023-08-21 18:42 UTC, GSemikozov submitted a review, later dismissed

2023-08-21 18:42 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-08-24 21:43 UTC, GSemikozov approved these changes

2023-08-24 21:43 UTC, merged