scss
js-tasks-ru/htmlcss-20230714_evgeniav pull request #30
Opened 2023-10-18 11:23 UTC by jennievv

2023-10-18 11:24 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-22 19:36 UTC, GSemikozov requested changes

2023-10-22 19:36 UTC, GSemikozov commented on assets/scss/_accordion.scss
> +        &__item:last-child{
&:last-child

2023-10-22 19:36 UTC, GSemikozov commented on assets/scss/_accordion.scss
> +        &__item[open] .accordion__svg {
&[open] .accordion__svg

2023-10-22 19:36 UTC, GSemikozov commented on assets/scss/_accordion.scss
> +        &__item:last-child{
и такая проблема везде ниже по коду)

2023-10-22 19:36 UTC, GSemikozov commented on assets/scss/_burger-menu.scss
> +    @media (max-width: 375px){
медиа запросы лучше писать точечно под элементами. Но - можно и так

2023-10-29 17:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-29 19:17 UTC, GSemikozov approved these changes

2023-10-29 19:17 UTC, merged