Skeleton
js-tasks-ru/htmlcss-20230714_evgeniav pull request #6
Opened 2023-07-31 17:17 UTC by jennievv

2023-07-31 17:18 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-01 15:34 UTC, GSemikozov requested changes

2023-08-01 15:34 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    max-width: 579px;
лишнее ограничение

2023-08-01 15:34 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__group  > .skeleton__element{
лучше как .skeleton__circle

2023-08-01 15:34 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__group  > .skeleton__column div:first-child{
не стоит использовать вложенные селекторы и через них определять ширину элементов - а вдруг у нас пеоменяется разметка / структура? тогда придется и стили переписывать. Лучше пользоваться модификаторами - .skeleton__column-small, .skeleton__column_large и тд + ширину в процентах (можно приблизительно)

2023-08-03 17:30 UTC, jennievv commented on 04-lection2/02-skeleton/skeleton.css
> +    max-width: 579px;
Почему? Как мне понимать, в какой момент мне указать ширину нужно, в какой не надо, в какой жестко width, а в какой-то только max-width, либо min-width, а ведь еще все это комбинировать можно? Мне же нужно как-то размер задать для элемента, у него же есть ширина(и эта ширина указана в макете), я же не могу ее просто не задавать, ведь тогда у меня элемент растянется и он уже выглядеть будет даже как непонятно что. Я заметила, что про ширину Вы мне несколько раз писали, что не стоит ограничивать или как сейчас, что лишнее ограничение, и у меня с этим проблема. Не знаю, может на таком примере будет понятнее, что мне непонятно: в английском есть "many", есть "much", а еще "a lot of", все обозначают много, но только "many" используется с исчисляемыми существительными, "much" с неисчисляемыми, а "a lot of" так вообще и комбинируется и еще что-то. И вот понимаете мне бы с шириной понять как ее использовать, и элементы-то разные бывают: есть кнопочка и в ней как бы и нет ничего кроме текста, а есть меню с аж несколькими ссылками, есть модальное окно регистрации, а в нем куча всяких заголовков, инпутов, кнопок, и у них у всех ширина какая-то есть помимо общей ширины всего элемента, в котором они лежат. Не знаю, может Вы мне объясните или может знаете какие-то ссылки, где эта разница разъяснена? Да плюс помимо ширины, я так поняла теперь, что высоту я тоже не понимаю как использовать

2023-08-03 22:11 UTC, jennievv commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__group  > .skeleton__element{
Не поняла, а как так можно задавать геометрические названия? Они ведь не несут в себе никакого смысла, одно дело, например, я называю text или title, они сами за себя говорят, а другое дело circle, круг - а круг это что, толи картинка ввиде круга, то ли аватарка, то ли что-то другое. Вообще я когда задание делала, то сейчас вроде вспоминаю, что называла circle, но все же решила, что так неправильно, и удалила такое название и вроде не сохраняла это вариант

2023-08-03 22:14 UTC, jennievv commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__group  > .skeleton__column div:first-child{
Много вложенных селекторов получилось, потому что пришлось выкручиваться. Как мне нужно было делать? Я все флексы, кроме `skeleton` и под него флекс-контейнер `skeleton__row`, сделала по-другому принципу: есть элемент `skeleton__group`, который я и делаю флекс-контейнером, не создавая флекс-контейнер внутри блока. Или все-таки нужно было под каждый блок флекс-контейнер создавать? Из-за того как сделала я, получилось, что мне стили для флекс-элементов приходилось задавать от их флекс-контейнера=блока, а не от просто блока, и тут получается, что названия-то у них одинаковые, а мне нужно выделить какой именно элемент в каком именно блоке я выбираю, и плюс ко всему этому я и флекс элементам-то названия тоже одинаковые задавала.
Про модификаторы я поняла, что они используются, когда нужно выделить какие-то небольшие реально отличающиеся от всего блоки или элементы, а не писать их для всех отличающихся мест, это тогда у меня каша будет из модификаторов.

2023-08-21 18:45 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__group  > .skeleton__element{
можно назвать .skeleton__avatar

2023-08-21 18:46 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__group  > .skeleton__element{
а вот .skeleton__element - намного более абстрактный класс, даже если сравнивать с .skeleton__circle)

2023-08-27 07:47 UTC, GSemikozov requested changes

2023-08-27 07:47 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__bottom_bottom{
если задать gap на уровне skeleton__bottom, то этот класс не нужен

2023-08-30 22:33 UTC, GSemikozov approved these changes

2023-08-30 22:33 UTC, merged